vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_images%'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
