easy_admin:
    entities:
        Tag:
            class: App\Entity\Tag
            form:
                fields: ['name', 'cssClass']

            list:
                fields: ['name', 'cssClass']
