easy_admin:
    entities:
        Techno:
            class: App\Entity\Techno
            form:
                fields: ['name', 'cssClass']

            list:
                fields: ['name', 'cssClass']
